spring:
  datasource:
    url: jdbc:h2:mem:blattschuss
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true